### ISSUE TITLE
Not working with latest rpi firmware update

### ISSUE THREAD

**Issue by cmarty** [brynthomas/omx_image#1]
Hello.
After update to the latest raspberry pi firmware (with rpi-update) the omx_image loader stop(stuck) loading image around line 575 in omx_image.c (OMX_UseEGLImage).
Last Rpi firmware that omx_image was working was Commits on Sep 26, 2016 :
https://github.com/Hexxeh/rpi-firmware/commit/d26c39bd353eb0ebbc7db3546277083eac4aa3bd
After next commit https://github.com/Hexxeh/rpi-firmware/commit/667cfabe63bc663383559ef88317e86f9bd41e45 it is not working.
I'm not able to find what is wrong with that.

**Comment by brynthomas** [comment]
Which version of the Pi are you using? I can't promise anything, but I'll try (at some point) to have a look and see what might have changed. Does it do it for all JPG images?

**Comment by cmarty** [comment]
I'm testing it on Rpi 3 but I am able to test it on Rpi 2 and Rpi B+. 
It happens for all jpegs..
It is good advice to test it on different Rpi. I will do it and let you know.

**Comment by Lvroz** [comment]
Hi,
I have the same problem,
I commented line 575 of omx_image.c as cmarty suggested, and it works, but I don't know on what conditions.
I got this back trace when debugging:
#0  0x76ebd7a4 in __pthread_cond_wait (cond=0x26a80 <omx_event_list+1576>, mutex=0x26a68 <omx_event_list+1552>) at pthread_cond_wait.c:187
#1  0x000125e8 in omx_event_wait_group (groupid=1, abort_on_error=1, timeout_s=0) at omx_event_and_buffer_handler.c:204
#2  0x000143cc in omx_image_loader (texture_id=1, i_eglDisplay=0x26328 <_state+16>, i_eglContext=0x26330 <_state+24>, force_width=0, force_height=0, output_width=0x0, output_height=0x0, image_format=JPEG, input_buffer=0x7effef60)
    at omx_image.c:575
#3  0x0001525c in init_textures (state=0x26318 <_state>) at triangle.c:409
#4  0x00015a88 in main () at triangle.c:549

Thank you for your work, it is very helpful.

**Comment by cmarty** [comment]
I have tested it also on Rpi 2 and it has the same problem.

**Comment by cmarty** [comment]
Thanks for patch. Now it is working ok. Thanks also for detailed explanation of the problem.
